apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 30
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "yourpassword"
          volumeMounts:
            - name: my-volume
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: my-volume
          emptyDir: {}
