apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
        - name: result-app
          image: keicee32/result-app
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
