apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - name: vote-app
          image: keicee32/vote-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
